var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var SUBADMIN_SCHEMA = {};
SUBADMIN_SCHEMA.SUBADMIN = {
  email: { type: String, lowercase: true, index: { unique: true }, trim: true },
  password: String,
  image: { type: String, default: '' },
  name: { type: String, default: '' },
  last_name: { type: String, default: '' },
  site_url: { type: String, default: '' },
  site_title: { type: String, default: '' },
  site_logo: { type: String, default: '' },
  user_prefix: { type: String, default: '' },
  role: { type: String, default: '' },
  status: { type: Number, default: 1 },
  components: { type: Boolean, default: false },
  users: { type: Boolean, default: false },
  products: { type: Boolean, default: false },
  orders: { type: Boolean, default: false },
  orderDelete: { type: Boolean, default: false },
  userView: { type: Boolean, default: false },
  userEdit: { type: Boolean, default: false },
  userDelete: { type: Boolean, default: false },
  productDelete: { type: Boolean, default: false },
  productView: { type: Boolean, default: false },
  productEdit: { type: Boolean, default: false },
  utilities: { type: Boolean, default: false },
  utilitiContact: { type: Boolean, default: false },
  contactDelete: { type: Boolean, default: false },
  contactCreate: { type: Boolean, default: false },
  contactEdit: { type: Boolean, default: false },
  contactView: { type: Boolean, default: false },
  utilitiForm: { type: Boolean, default: false },
  utilitiPricing: { type: Boolean, default: false },
  pricingCreate: { type: Boolean, default: false },
  pricingEdit: { type: Boolean, default: false },
  pricingDelete: { type: Boolean, default: false },
  utilitiRole: { type: Boolean, default: false },
  roleCreate: { type: Boolean, default: false },
  roleEdit: { type: Boolean, default: false },
  roleDelete: { type: Boolean, default: false },
  utilitiSkill: { type: Boolean, default: false },
  skillCreate: { type: Boolean, default: false },
  skillEdit: { type: Boolean, default: false },
  skillDelete: { type: Boolean, default: false },
  opening_hours: {
    workingDays: { type: String, default: '' },
    workingDaysSaturday: { type: String, default: '' },
    workingDaysSunday: { type: String, default: '' },
  },
  privileges: [],
  activity: {
    last_login: { type: Date, default: Date.now },
    last_logout: { type: Date, default: Date.now },
  },
  reset_code: String,
  time_stamps: Number,
  otp: Number /* 6 digits */,
  otp_timestamp: Number /* add 5 mins with current timestamp */,
  otp_verified: Number,
  uuid: String,
};
module.exports = SUBADMIN_SCHEMA;
